# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_buscar_recibos.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 352)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 701, 331))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.buscar = QtWidgets.QWidget()
        self.buscar.setObjectName("buscar")
        self.rutas = QtWidgets.QGroupBox(self.buscar)
        self.rutas.setGeometry(QtCore.QRect(20, 10, 671, 121))
        self.rutas.setTitle("")
        self.rutas.setObjectName("rutas")
        self.lbl_control = QtWidgets.QLabel(self.rutas)
        self.lbl_control.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.lbl_control.setStyleSheet("")
        self.lbl_control.setObjectName("lbl_control")
        self.control_input = QtWidgets.QLineEdit(self.rutas)
        self.control_input.setGeometry(QtCore.QRect(130, 10, 481, 20))
        self.control_input.setObjectName("control_input")
        self.lbl_destino = QtWidgets.QLabel(self.rutas)
        self.lbl_destino.setGeometry(QtCore.QRect(10, 90, 111, 21))
        self.lbl_destino.setObjectName("lbl_destino")
        self.ruta_destino_input = QtWidgets.QLineEdit(self.rutas)
        self.ruta_destino_input.setGeometry(QtCore.QRect(130, 90, 481, 21))
        self.ruta_destino_input.setObjectName("ruta_destino_input")
        self.lbl_periodo_ini = QtWidgets.QLabel(self.rutas)
        self.lbl_periodo_ini.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.lbl_periodo_ini.setObjectName("lbl_periodo_ini")
        self.periodo_inicial = QtWidgets.QLineEdit(self.rutas)
        self.periodo_inicial.setGeometry(QtCore.QRect(130, 50, 31, 20))
        self.periodo_inicial.setMaxLength(2)
        self.periodo_inicial.setCursorPosition(1)
        self.periodo_inicial.setAlignment(QtCore.Qt.AlignCenter)
        self.periodo_inicial.setReadOnly(False)
        self.periodo_inicial.setObjectName("periodo_inicial")
        self.lbl_periodo_final = QtWidgets.QLabel(self.rutas)
        self.lbl_periodo_final.setGeometry(QtCore.QRect(240, 50, 91, 21))
        self.lbl_periodo_final.setObjectName("lbl_periodo_final")
        self.lbl_guion = QtWidgets.QLabel(self.rutas)
        self.lbl_guion.setGeometry(QtCore.QRect(220, 50, 21, 21))
        self.lbl_guion.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_guion.setObjectName("lbl_guion")
        self.sb_a_ini = QtWidgets.QSpinBox(self.rutas)
        self.sb_a_ini.setGeometry(QtCore.QRect(170, 50, 51, 21))
        self.sb_a_ini.setMinimum(2014)
        self.sb_a_ini.setMaximum(9999)
        self.sb_a_ini.setObjectName("sb_a_ini")
        self.periodo_final = QtWidgets.QLineEdit(self.rutas)
        self.periodo_final.setGeometry(QtCore.QRect(330, 50, 31, 20))
        self.periodo_final.setMaxLength(2)
        self.periodo_final.setCursorPosition(1)
        self.periodo_final.setAlignment(QtCore.Qt.AlignCenter)
        self.periodo_final.setReadOnly(False)
        self.periodo_final.setObjectName("periodo_final")
        self.sb_a_fin = QtWidgets.QSpinBox(self.rutas)
        self.sb_a_fin.setGeometry(QtCore.QRect(370, 50, 51, 21))
        self.sb_a_fin.setMinimum(2014)
        self.sb_a_fin.setMaximum(9999)
        self.sb_a_fin.setObjectName("sb_a_fin")
        self.lbl_guion.raise_()
        self.lbl_control.raise_()
        self.control_input.raise_()
        self.lbl_destino.raise_()
        self.ruta_destino_input.raise_()
        self.lbl_periodo_ini.raise_()
        self.periodo_inicial.raise_()
        self.lbl_periodo_final.raise_()
        self.sb_a_ini.raise_()
        self.periodo_final.raise_()
        self.sb_a_fin.raise_()
        self.opciones = QtWidgets.QGroupBox(self.buscar)
        self.opciones.setGeometry(QtCore.QRect(20, 140, 281, 141))
        self.opciones.setObjectName("opciones")
        self.op_recuperar_ubicaciones = QtWidgets.QCheckBox(self.opciones)
        self.op_recuperar_ubicaciones.setEnabled(True)
        self.op_recuperar_ubicaciones.setGeometry(QtCore.QRect(10, 30, 191, 31))
        self.op_recuperar_ubicaciones.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.op_recuperar_ubicaciones.setAutoFillBackground(False)
        self.op_recuperar_ubicaciones.setCheckable(True)
        self.op_recuperar_ubicaciones.setChecked(False)
        self.op_recuperar_ubicaciones.setTristate(False)
        self.op_recuperar_ubicaciones.setObjectName("op_recuperar_ubicaciones")
        self.op_pdf_unico = QtWidgets.QCheckBox(self.opciones)
        self.op_pdf_unico.setGeometry(QtCore.QRect(10, 110, 191, 17))
        self.op_pdf_unico.setObjectName("op_pdf_unico")
        self.op_extraer_hoja_indiv = QtWidgets.QCheckBox(self.opciones)
        self.op_extraer_hoja_indiv.setGeometry(QtCore.QRect(10, 70, 191, 17))
        self.op_extraer_hoja_indiv.setObjectName("op_extraer_hoja_indiv")
        self.boton_start = QtWidgets.QPushButton(self.buscar)
        self.boton_start.setGeometry(QtCore.QRect(410, 180, 171, 51))
        self.boton_start.setStyleSheet("")
        self.boton_start.setObjectName("boton_start")
        self.tabWidget.addTab(self.buscar, "")
        self.metadatos = QtWidgets.QWidget()
        self.metadatos.setObjectName("metadatos")
        self.carpeta_input = QtWidgets.QLineEdit(self.metadatos)
        self.carpeta_input.setGeometry(QtCore.QRect(80, 20, 481, 20))
        self.carpeta_input.setObjectName("carpeta_input")
        self.carpeta_text = QtWidgets.QLabel(self.metadatos)
        self.carpeta_text.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.carpeta_text.setObjectName("carpeta_text")
        self.boton_start_mt = QtWidgets.QPushButton(self.metadatos)
        self.boton_start_mt.setGeometry(QtCore.QRect(200, 70, 141, 41))
        self.boton_start_mt.setStyleSheet("")
        self.boton_start_mt.setObjectName("boton_start_mt")
        self.tabWidget.addTab(self.metadatos, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Copy  Recibos - Timbres"))
        self.lbl_control.setText(_translate("MainWindow", "NUMERO DE CONTROL"))
        self.lbl_destino.setText(_translate("MainWindow", "CARPETA DESTINO"))
        self.lbl_periodo_ini.setText(_translate("MainWindow", "PERIODOS INICIAL"))
        self.periodo_inicial.setText(_translate("MainWindow", "1"))
        self.lbl_periodo_final.setText(_translate("MainWindow", "PERIODOS FINAL"))
        self.lbl_guion.setText(_translate("MainWindow", "  -  "))
        self.periodo_final.setText(_translate("MainWindow", "1"))
        self.opciones.setTitle(_translate("MainWindow", "OPCIONES"))
        self.op_recuperar_ubicaciones.setText(_translate("MainWindow", "UBICACIONES EN HOJAS"))
        self.op_pdf_unico.setText(_translate("MainWindow", "EXTRAER EN PDF UNICO"))
        self.op_extraer_hoja_indiv.setText(_translate("MainWindow", "EXTRAER EN PDF INDIVIDUAL"))
        self.boton_start.setText(_translate("MainWindow", "BUSCAR RECIBOS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buscar), _translate("MainWindow", "BUSCADOR DE RECIBOS EN PDF"))
        self.carpeta_text.setText(_translate("MainWindow", "RECIBOS"))
        self.boton_start_mt.setText(_translate("MainWindow", "EMPEZAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.metadatos), _translate("MainWindow", "CREACION DE METADATOS"))
