# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz_buscar_recibos.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 405)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 701, 401))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.buscar = QtWidgets.QWidget()
        self.buscar.setObjectName("buscar")
        self.rutas = QtWidgets.QGroupBox(self.buscar)
        self.rutas.setGeometry(QtCore.QRect(20, 10, 671, 101))
        self.rutas.setTitle("")
        self.rutas.setObjectName("rutas")
        self.control_text = QtWidgets.QLabel(self.rutas)
        self.control_text.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.control_text.setObjectName("control_text")
        self.control_input = QtWidgets.QLineEdit(self.rutas)
        self.control_input.setGeometry(QtCore.QRect(130, 10, 481, 20))
        self.control_input.setObjectName("control_input")
        self.text_destino = QtWidgets.QLabel(self.rutas)
        self.text_destino.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.text_destino.setObjectName("text_destino")
        self.ruta_destino = QtWidgets.QLineEdit(self.rutas)
        self.ruta_destino.setGeometry(QtCore.QRect(130, 40, 481, 20))
        self.ruta_destino.setObjectName("ruta_destino")
        self.opciones = QtWidgets.QGroupBox(self.buscar)
        self.opciones.setGeometry(QtCore.QRect(20, 120, 281, 171))
        self.opciones.setObjectName("opciones")
        self.op_recuperar_ubicaciones = QtWidgets.QCheckBox(self.opciones)
        self.op_recuperar_ubicaciones.setEnabled(True)
        self.op_recuperar_ubicaciones.setGeometry(QtCore.QRect(10, 30, 191, 31))
        self.op_recuperar_ubicaciones.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.op_recuperar_ubicaciones.setAutoFillBackground(False)
        self.op_recuperar_ubicaciones.setCheckable(True)
        self.op_recuperar_ubicaciones.setChecked(False)
        self.op_recuperar_ubicaciones.setTristate(False)
        self.op_recuperar_ubicaciones.setObjectName("op_recuperar_ubicaciones")
        self.op_comprimir = QtWidgets.QCheckBox(self.opciones)
        self.op_comprimir.setGeometry(QtCore.QRect(10, 110, 191, 17))
        self.op_comprimir.setObjectName("op_comprimir")
        self.op_extraer_hoja_indiv = QtWidgets.QCheckBox(self.opciones)
        self.op_extraer_hoja_indiv.setGeometry(QtCore.QRect(10, 70, 191, 17))
        self.op_extraer_hoja_indiv.setObjectName("op_extraer_hoja_indiv")
        self.boton_start = QtWidgets.QPushButton(self.buscar)
        self.boton_start.setGeometry(QtCore.QRect(400, 190, 171, 51))
        self.boton_start.setStyleSheet("")
        self.boton_start.setObjectName("boton_start")
        self.tabWidget.addTab(self.buscar, "")
        self.metadatos = QtWidgets.QWidget()
        self.metadatos.setObjectName("metadatos")
        self.carpeta_input = QtWidgets.QLineEdit(self.metadatos)
        self.carpeta_input.setGeometry(QtCore.QRect(80, 20, 481, 20))
        self.carpeta_input.setObjectName("carpeta_input")
        self.carpeta_text = QtWidgets.QLabel(self.metadatos)
        self.carpeta_text.setGeometry(QtCore.QRect(20, 20, 51, 16))
        self.carpeta_text.setObjectName("carpeta_text")
        self.boton_start_2 = QtWidgets.QPushButton(self.metadatos)
        self.boton_start_2.setGeometry(QtCore.QRect(200, 70, 141, 41))
        self.boton_start_2.setStyleSheet("")
        self.boton_start_2.setObjectName("boton_start_2")
        self.tabWidget.addTab(self.metadatos, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Copy  Recibos - Timbres"))
        self.control_text.setText(_translate("MainWindow", "NUMERO DE CONTROL"))
        self.text_destino.setText(_translate("MainWindow", "CARPETA DESTINO"))
        self.opciones.setTitle(_translate("MainWindow", "OPCIONES"))
        self.op_recuperar_ubicaciones.setText(_translate("MainWindow", "UBICACIONES EN HOJAS"))
        self.op_comprimir.setText(_translate("MainWindow", "EXTRAER EN PDF UNICO"))
        self.op_extraer_hoja_indiv.setText(_translate("MainWindow", "EXTRAER EN PDF INDIVIDUAL"))
        self.boton_start.setText(_translate("MainWindow", "BUSCAR RECIBOS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.buscar), _translate("MainWindow", "BUSCADOR DE RECIBOS EN PDF"))
        self.carpeta_text.setText(_translate("MainWindow", "RECIBOS"))
        self.boton_start_2.setText(_translate("MainWindow", "EMPEZAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.metadatos), _translate("MainWindow", "CREACION DE METADATOS"))
